name: Build packages
on: push
jobs:
  build:
    env:
      CCACHE_COMPILERCHECK: content
      CCACHE_DIR: /tmp/ccache
      PACKAGER_PRIVKEY: /tmp/cfsworks@gmail.com-6549341f.rsa
      PRIVKEY_CONTENT: ${{ secrets.PRIVATEKEY }}
      USE_CCACHE: '1'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Preserve ccache
        uses: actions/cache@v3
        with:
          path: /tmp/ccache
          key: ccache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: ccache-${{ runner.os }}

      - name: Setup Alpine Linux edge
        uses: jirutka/setup-alpine@v1
        with:
          branch: edge
          packages: >
            alpine-sdk
            ccache
            gcc-aarch64-none-elf
          volumes: /tmp:/tmp

      - name: Get packager key set up
        run: |
          echo "$PRIVKEY_CONTENT" > $PACKAGER_PRIVKEY
          openssl rsa -pubout -in $PACKAGER_PRIVKEY > $PACKAGER_PRIVKEY.pub
        shell: alpine.sh {0}

      - name: Add runner to abuild group, and set up build environment
        run: |
          adduser runner abuild
          ln -s $(which ccache) /usr/lib/ccache/bin/aarch64-none-elf-gcc
          cp -ra /usr/lib/gcc/*alpine*/*/plugin/include/cp/* /usr/lib/gcc/aarch64-none-elf/*/plugin/include/cp/
        shell: alpine.sh --root {0}

      - name: Run build for linux-lts
        run: |
          cd main/linux-lts
          CHOST=aarch64-none-elf CBUILDROOT=/ CARCH=aarch64 BOOTSTRAP=no abuild -r
        shell: alpine.sh {0}
